//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NevoX.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NevoX.Localization.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Account_Field_Email {
            get {
                return ResourceManager.GetString("Account_Field_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        internal static string Account_Field_Password {
            get {
                return ResourceManager.GetString("Account_Field_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre mot de passe et/ou votre email..
        /// </summary>
        internal static string Authentication_Alert_Credential {
            get {
                return ResourceManager.GetString("Authentication_Alert_Credential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre connexion internet pour vous connecter.
        /// </summary>
        internal static string Authentication_Alert_Network {
            get {
                return ResourceManager.GetString("Authentication_Alert_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion en cours ....
        /// </summary>
        internal static string Authentication_Message_InProgress {
            get {
                return ResourceManager.GetString("Authentication_Message_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe:.
        /// </summary>
        internal static string Login_PasswordTitleLabel {
            get {
                return ResourceManager.GetString("Login_PasswordTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        internal static string Login_SignIn {
            get {
                return ResourceManager.GetString("Login_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNEXION.
        /// </summary>
        internal static string Login_SignInTitle {
            get {
                return ResourceManager.GetString("Login_SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login !!!!!!!.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Login_UsernameTitleLabel {
            get {
                return ResourceManager.GetString("Login_UsernameTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIXEM.
        /// </summary>
        internal static string Logo_Title {
            get {
                return ResourceManager.GetString("Logo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string NetworkConnection_Alert_Confirm {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires access to remote data, but you don&apos;t seem to currently have a network connnection. Check your connection and try again..
        /// </summary>
        internal static string NetworkConnection_Alert_Message {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non connecté.
        /// </summary>
        internal static string NetworkConnection_Alert_Title {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        internal static string Splash_NewAccount {
            get {
                return ResourceManager.GetString("Splash_NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        internal static string Splash_SignIn {
            get {
                return ResourceManager.GetString("Splash_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splash !!!!!!!.
        /// </summary>
        internal static string Splash_Title {
            get {
                return ResourceManager.GetString("Splash_Title", resourceCulture);
            }
        }
    }
}
